import org.jetbrains.kotlin.gradle.dsl.JvmTarget

apply plugin: 'com.android.application'

//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.

// Custom definitions may go here
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://repo.dairy.foundation/releases"
        }
    }
    dependencies {
        classpath "dev.frozenmilk:Load:0.3.1"
    }
}

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'dev.frozenmilk.sinister.sloth.load'

android {
    namespace = 'org.firstinspires.ftc.teamcode'


    defaultConfig {
        minSdk 24
    }

    packagingOptions {
        jniLibs {
            pickFirsts += ['**/*.so']
        }
        jniLibs.useLegacyPackaging true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation project(':FtcRobotController')
    implementation 'dev.nextftc.v2:control:0.2.0'
    implementation 'dev.nextftc.v2:hardware:0.2.0'
    implementation 'dev.nextftc.v2:robot:0.2.0'
    implementation "com.bylazar:battery:1.0.3"
    implementation "com.bylazar:camerastream:1.0.0"
    implementation "com.bylazar:capture:1.0.3"
    implementation "com.bylazar:configurables:1.0.5"
    implementation "com.bylazar:field:1.0.7"
    implementation "com.bylazar:fullpanels:1.0.13"
    implementation "com.bylazar:gamepad:1.0.4"
    implementation "com.bylazar:graph:1.0.4"
    implementation "com.bylazar:lights:1.0.3"
    implementation "com.bylazar:limelightproxy:1.0.4"
    implementation "com.bylazar:opmodecontrol:1.0.3"
    implementation "com.bylazar:pinger:1.0.3"
    implementation "com.bylazar:telemetry:1.0.5"
    implementation "com.bylazar:themes:1.0.3"
    implementation "com.bylazar:utils:1.0.4"
    implementation 'dev.nextftc.v2:control:0.2.1'
    implementation 'dev.nextftc.v2:hardware:0.2.1'
    implementation 'dev.nextftc.v2:robot:0.2.1'
}
